language: erlang
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install python-dev libffi-dev libssl-dev
  - sudo apt-get install python-virtualenv lua5.1
  - sudo add-apt-repository -y ppa:bartbes/love-stable
  - sudo apt-get update -y -f
  - sudo apt-get install -y love
  - mkdir -p $TRAVIS_BUILD_DIR/share/love/
env:
  global:
  - XDG_DATA_HOME="$TRAVIS_BUILD_DIR/share"
script: make deploy
addons:
  artifacts:
    paths:
      - ./build/hawkthorne-osx.zip
      - ./build/hawkthorne-win-x86.zip
      - ./build/hawkthorne.love
